# Generated by Django 6.0.3 on 2026-03-24 19:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetgoal',
            options={'verbose_name_plural': 'Budget Goals'},
        ),
        migrations.RemoveField(
            model_name='budgetgoal',
            name='user',
        ),
        migrations.AddField(
            model_name='budgetgoal',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budget_goals', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
