# Generated by Django 6.0.3 on 2026-03-24 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_budgetgoal_options_remove_budgetgoal_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetgoal',
            name='account',
        ),
        migrations.AddField(
            model_name='budgetgoal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budget_goals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
