# Generated by Django 6.0.3 on 2026-03-24 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('budgets', '0003_remove_budgetgoal_account_budgetgoal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetgoal',
            old_name='target_amount',
            new_name='allocated_amount',
        ),
        migrations.RemoveField(
            model_name='budgetgoal',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='budgetgoal',
            name='related_transactions',
        ),
        migrations.AddField(
            model_name='budgetgoal',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='budget_goals', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetgoal',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
