# Generated by Django 6.0.3 on 2026-03-24 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_rename_target_amount_budgetgoal_allocated_amount_and_more'),
        ('transactions', '0002_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='budget_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budgets.budgetgoal'),
        ),
    ]
